# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Graphviz system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev     # provides /usr/bin/dot etc.
      - name: Install dependencies
        run: |          
          python -m pip install --upgrade pip          
          pip install flake8 pytest
          pip install "git+https://github.com/kyberszittya/himeko_hypergraph@v0.1.2#egg=himeko"
          cd himeko_lang_core
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          cd himeko_lang_core
          # stop the build if there are Python syntax errors or undefined names
          #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --verbose
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          cd himeko_lang_core
          # Add current directory to PYTHONPATH so that pytest can find the himeko package
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest
